[package]
name = "polychat-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "polychat_core"
path = "src/lib.rs"
crate-type = ["rlib", "dylib"]


[dependencies]
libloading = "0.7.3"
polychat-plugin = "0.1.0"

[build-dependencies]
polychat-plugin = "0.1.0"
cc = "1.0.72"